INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   4590
        Validation size: 509
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: True
Epoch 1/5:   0%|                                                                                                                                             | 0/4590 [00:33<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    amp=args.amp)
  File "train.py", line 92, in train_net
    masks_pred = net(images)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\내 드라이브\인턴\도로 크랙 탐지\Pytorch-UNet\unet\unet_model.py", line 34, in forward
    x = self.up4(x, x1)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\내 드라이브\인턴\도로 크랙 탐지\Pytorch-UNet\unet\unet_parts.py", line 57, in forward
    x1 = self.up(x1)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\modules\upsampling.py", line 141, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\functional.py", line 3163, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, sfl[0], sfl[1])
RuntimeError: CUDA out of memory. Tried to allocate 76.00 MiB (GPU 0; 2.00 GiB total capacity; 1.18 GiB already allocated; 0 bytes free; 1.24 GiB reserved in total by PyTorch)