INFO: Starting training:
        Epochs:          5
        Batch size:      8
        Learning rate:   1e-05
        Training size:   8017
        Validation size: 2004
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: True
Epoch 1/5:   0%|                                                                                                                                                                                                | 0/8017 [00:00<?, ?img/s]C:\Users\chank\anaconda3\envs\deep_learning\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)



Epoch 1/5:   1%|█▎                                                                                                                                                                  | 64/8017 [00:20<43:09,  3.07img/s, loss (batch)=1.13]
Traceback (most recent call last):
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
Traceback (most recent call last):
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
Traceback (most recent call last):
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
Traceback (most recent call last):
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 파이프가 닫히는 중입니다
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
BrokenPipeError: [WinError 232] 파이프가 닫히는 중입니다
BrokenPipeError: [WinError 232] 파이프가 닫히는 중입니다
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 파이프가 닫히는 중입니다
INFO: Saved interrupt