INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   9019
        Validation size: 1002
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: False
Epoch 1/5:   0%|          | 0/9019 [38:24<?, ?img/s]
INFO: Saved interrupt
Traceback (most recent call last):
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 파이프가 닫히는 중입니다
Traceback (most recent call last):
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\queues.py", line 238, in _feed
    send_bytes(obj)
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "C:\Users\chank\anaconda3\envs\deep_learning\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 파이프가 닫히는 중입니다